- name: Reading unseal key contents
  command: cat {{item}}
  register: seal_keys
  with_fileglob: "{{ seal_keys_dir_output }}/*"
  delegate_to: localhost
  become: no

- name: Unseal vault with unseal keys
  shell: |
    vault operator seal {{ item.stdout }}
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"
  with_items: "{{seal_keys.results}}"
